#Grasshopper - Summation
"""
Summation
Write a program that finds the summation of every number from 1 to num. The number will always be a positive integer greater than 0.

For example (Input -> Output):

2 -> 3 (1 + 2)
8 -> 36 (1 + 2 + 3 + 4 + 5 + 6 + 7 + 8)
FUNDAMENTALSMATHEMATICS"""
#Solution
def summation(num):
    pass # Code here
    return (num*(num+1))/2;
#OUTPUTS
"""
Time: 560ms Passed: 105Failed: 0
Test Results:
Fixed tests
Basic Test Cases
 (5 of 5 Assertions)
Completed in 0.10ms
Random tests
Testing for summation(259)
Testing for summation(209)
Testing for summation(359)
Testing for summation(179)
Testing for summation(485)
Testing for summation(384)
Testing for summation(123)
Testing for summation(264)
Testing for summation(221)
Testing for summation(28)
Testing for summation(494)
Testing for summation(126)
Testing for summation(487)
Testing for summation(274)
Testing for summation(236)
Testing for summation(421)
Testing for summation(67)
Testing for summation(339)
Testing for summation(94)
Testing for summation(182)
Testing for summation(251)
Testing for summation(302)
Testing for summation(396)
Testing for summation(463)
Testing for summation(210)
Testing for summation(221)
Testing for summation(325)
Testing for summation(361)
Testing for summation(178)
Testing for summation(299)
Testing for summation(400)
Testing for summation(28)
Testing for summation(212)
Testing for summation(422)
Testing for summation(164)
Testing for summation(146)
Testing for summation(269)
Testing for summation(139)
Testing for summation(120)
Testing for summation(55)
Testing for summation(206)
Testing for summation(487)
Testing for summation(14)
Testing for summation(136)
Testing for summation(151)
Testing for summation(412)
Testing for summation(416)
Testing for summation(456)
Testing for summation(226)
Testing for summation(358)
Testing for summation(141)
Testing for summation(300)
Testing for summation(51)
Testing for summation(436)
Testing for summation(346)
Testing for summation(429)
Testing for summation(20)
Testing for summation(245)
Testing for summation(9)
Testing for summation(346)
Testing for summation(173)
Testing for summation(470)
Testing for summation(315)
Testing for summation(128)
Testing for summation(172)
Testing for summation(286)
Testing for summation(440)
Testing for summation(65)
Testing for summation(159)
Testing for summation(436)
Testing for summation(385)
Testing for summation(330)
Testing for summation(237)
Testing for summation(17)
Testing for summation(262)
Testing for summation(168)
Testing for summation(343)
Testing for summation(78)
Testing for summation(379)
Testing for summation(325)
Testing for summation(176)
Testing for summation(99)
Testing for summation(12)
Testing for summation(270)
Testing for summation(355)
Testing for summation(434)
Testing for summation(72)
Testing for summation(181)
Testing for summation(331)
Testing for summation(23)
Testing for summation(487)
Testing for summation(229)
Testing for summation(239)
Testing for summation(235)
Testing for summation(134)
Testing for summation(123)
Testing for summation(309)
Testing for summation(84)
Testing for summation(438)
Testing for summation(354)
Completed in 5.67ms
You have passed all of the tests! :)"""