#MAKE UPPERCASE
"""
Write a function which converts the input string to uppercase.

FUNDAMENTALSSTRINGS"""
#Solution
def make_upper_case(s):
    # Code here
    return s.upper()
#OUTPUTS
"""
Time: 621ms Passed: 100Failed: 0
Test Results:
Fixed Tests
Basic Test Cases
 (5 of 5 Assertions)
Completed in 0.08ms
Random Tests
testing for make-upper_case(UTnUza! oGsFgLr FBDB!6anII7 VWQv GSTLGYj sQotH 6d4x Z ZWhq S6bF)
testing for make-upper_case(O Vp Z yVqflsXtbU25ORtNBxyuU!CIu6zVzniX2oYRjR6lAF0V aA7cHYqdpPd5v2eH6DsrguJ2B)
testing for make-upper_case(h78ya3YYivwl)
testing for make-upper_case(ZQ48AfGQiNNJN9n7lV)
testing for make-upper_case(mP SO0p v8Bjc tU)
testing for make-upper_case(70L E1rCMgsJYJxRaFUt rDQ2vGH Ey VIQfUZtAktFcneyjIXaf j Pt VmDo Q RUG14NlY!R6LpHwARnhZrf XQu zj Cyj)
testing for make-upper_case(BLXrlGgyO4sH C87B16OHn nyr4nfuemooS kT5xzR QOFA8wD1SzqUy9h!yM2OepMX lH kU5PpSQ HS BoQ3pMlGlD Nqz2a)
testing for make-upper_case(QgYMrUl)
testing for make-upper_case(HvQ8XWs DLGt9XJ G1A07Gp5MFvquf6z tulyf2Xk  8qxaG X2XCy0JMSmPdXi7f l0lg0 Dfnubq15ICOkak)
testing for make-upper_case(Jxg8! PRlPpqyQWaCLN W4cBpa!9 Q7 ILutXDY5rehbjQSCOCfdqSaaYyYR4seRBxlfP3TG ogQf RFdBhpu)
testing for make-upper_case(HMNITM0NfC9TfUQD8kvSSj4V SpjSpdW6q WQ5jkM6bgBO6NV1VQH9AYWuAi4ahJsBoTDhG!47aR QWgzINyoQMJ)
testing for make-upper_case( lWY5NQwdMEl X SO7xi Ef4U01r XEmhtHE11CcW0fmHehnT8WDqh4M7 Pj dL O 4uzwTlZ FigH2 1x)
testing for make-upper_case(ZRevXzDXmuAfzXb7 Y2 Qhz1tWqU w!hGvTrQaQms973DdoUw 5 B N)
testing for make-upper_case(l79TdoovHVCiF1c xix8hIGgCxz6llM5 PPEhpVxfA)
testing for make-upper_case(StIa8 7vS 9Mt b D9NmJTGMuSJZePdJh4 2  HDsnkG5 YB YOBQ vSj6xRHbU14ystSl2dXk9QE5NPbR sx4rLQ 9QA )
testing for make-upper_case( wL4 4FE3BMM35 aZ!P0vgjlinvAwLjaN9 k8vn peuyiRYXDyku0!t!Gt35a LzvZUFy CdpvvLnQnGLXzVyRm)
testing for make-upper_case(ilNoNyjgAwPyIAZwm2CmuOj yw7wZTkOZC2j Ok8ae0)
testing for make-upper_case(L7e8GE8 0qV5QWX!OF)
testing for make-upper_case(fkdtaQ QtrAhI7d a7md XAL88uj!W3F4I m4dsZ 7HM2 GnOYl!PPdizjZb67V)
testing for make-upper_case(h si N8)
testing for make-upper_case(l)
testing for make-upper_case(PSH o7nQbHY3 xFkvnzVlbcMP4Lm Nn5GEfOkDSNAFw68c9lQ)
testing for make-upper_case(0MWeSQSIhAg WhMNs eOmhQotXV9UBixwTlHNQXZCdVk3pi2VbPjZxRk RDYnwQJ  zsnsgw1eu4rqW6tj)
testing for make-upper_case(FLkm3)
testing for make-upper_case(w6qSkHY7Yn a9 yG5ZLxZnC jIURPQGfqk7OcdGS u kH4gihPW Y hFkxIsW1zSrcOQ IU3sb8a !tC7GQVjoU)
testing for make-upper_case(5 5V0Gojo0NzhE2p2lL6BWswWfMUDSIMzzcrXRpdl S e3HkkMHLaRV6Xy nDg vSxtTj0gz)
testing for make-upper_case(VSgT1 j3RiO4NIp)
testing for make-upper_case(NPG g90R5)
testing for make-upper_case(zJp7cL5B4wZyV aYfPz5bGr3N Mo3yzRmDwRw4e5kuo69URtyMNM)
testing for make-upper_case(FCMDao 5 aqmduWmeiVm2VnhZ5!4)
testing for make-upper_case(CC 98 4uFNYZTCtD)
testing for make-upper_case(Gk1zOJh n LGUqrizjfAt o06SdJ2R P9ap7xmlBix!)
testing for make-upper_case(Q9vd WV5Fr QRFbpIME)
testing for make-upper_case(IQ8ikCezh936z8zlf NOLb xYPXJ0NwaDDU3PA4pgLfmxLOYCjIfRAeQ9 pB)
testing for make-upper_case(OWmMdE!W4ZXb1cAXWkD5mxrDwVVdNnmGj3mB a7NUpCb9FLDh g)
testing for make-upper_case( 5aSVApAtei Gug 4L  Yns ApNsuVrY9x!an!ISgd88znB PQG)
testing for make-upper_case(bLCkz!Tll QR7UUI4n3EzLDltz h B2)
testing for make-upper_case(Q Bp9NNvjnMCeOM ZZzF ZG zeFqV9W3N V81iPD yAbhY7 !oEuYY yONu pfdq8r8s6JXp4gCNLXBS6BD)
testing for make-upper_case(e0QUT)
testing for make-upper_case(uQU9f7E)
testing for make-upper_case(mE9Iaev EUxNJG6 PLoSN9Mmxqm)
testing for make-upper_case(pajxnrOrCZZNQfm vugA5BklRQG9DQJ1vwLQI1!S7 aHs y o)
testing for make-upper_case(B8e 7eYuGTeFGy lqq8WJnfxGvga9Rmvc330Rs)
testing for make-upper_case(ucQ7F7vciw)
testing for make-upper_case(sMY1kcm5mJkxTOd z3qfSdGzLDXc rp6gW!6usph)
testing for make-upper_case(N LmfApaF5k)
testing for make-upper_case(GuOZljUw IvM2xhqYpD8PL G3xPN1Z Cvw 2spDy l 2cG7 oENeIX19gc 7ZLR6c ! !XUvbr Tz)
testing for make-upper_case(ntQvbbZV!Hn9lHwHXuA 64GXeMueM 3rE!c269HqvNA3 gHIUSmHPv20NWAx!Pwxm r!m 23u8ETbx)
testing for make-upper_case(wIOIGMgx mN TevwS23Fm8a JO)
testing for make-upper_case(4p rQj2 LA xTs psX8F3R7yqWqY!Twk2C5Yju7EizQihBszmHwm4pAc19oUFTB hBUkEEpx cCQhuvq5)
testing for make-upper_case(N UzthggUfXS2)
testing for make-upper_case(mn rwr)
testing for make-upper_case(rqyvPC93)
testing for make-upper_case(gBprNlJO0sTTfkuZd pFTQp)
testing for make-upper_case(dLi2htwShCsW)
testing for make-upper_case(xVW7IFYdGP! w4 nf yNSAbAOHGypvZ9 NtWB4VnUF4QPZys VTn duaTqU2lCgqGYluAyL)
testing for make-upper_case(7PgEd6taDQ  RRM yeygrvpJL3lkhwFwEipYoRmWimk2hSFQT 9NR18j 4 50 z46s  jZclfuLQD 7XnVsIzVEP45 z)
testing for make-upper_case(QQitQ5sM8ft9Fj1LX5tXCf0hyV6HuDghk XYNGEPzN OPEYV1eQho9c8DPneSVI2R Uzu5)
testing for make-upper_case(18Z4z BWAkI7Cv P1UGilA1LlXDJdCx RDuoJv45nXOH3 dfr7CQ q bXc wC2o2ZAhIvqHtafqQ40hCC6nwx iN)
testing for make-upper_case(vbtvO!lOw!DiOuQpbel9u 0sh RNN nYmAEw!B3d8DsT!BT6XS2c8iJN 9  wD QtNT1V)
testing for make-upper_case(5wJ  u8vcTX45f2r)
testing for make-upper_case(gQjOUEch!R3)
testing for make-upper_case(!bfR6yfQlbf7k 6trSp JJ8pireY5xUC8wtoF)
testing for make-upper_case(SJqNh H O621Lo7yPDB)
testing for make-upper_case(U 1tFLAbG1ETYaG83 D   Nz 10d V)
testing for make-upper_case(pVgdTIrNSZqDBn OgY Chqep5nMNscQnMj8azZUtyG8E58jpEF1m72B FYRbB awdHqiUlxaI mW98ljCEA03HjuE6hiB3S)
testing for make-upper_case(wt4H3mMAWISt0eEi32WDG8VOc fBjwyX3w qOP bJ1 N r)
testing for make-upper_case(o8rl)
testing for make-upper_case(y!pR IDqYJSd FFP!1jorEsW)
testing for make-upper_case(QFh2HTsCr)
testing for make-upper_case(JuX!huWQOWfYw7C VpgmHoSIUWsjqQyMn jfII qfdblUx sAaDtSAODE4HOmvQwU!l QvQQJj)
testing for make-upper_case(BDQ5 H9NkffzA2o mQJg5zRhQ481LX 6V8DEa jQPi64 pCkf3XMwj b8U8rw4qsOXsQQ2i28f)
testing for make-upper_case(3vzPU0b 7kYCZ5fmCb2my8nfOe6 6 ffGB79Xst 6cD Bf! n LA 7O6pj2 1Q R!OJDZFmxqUp9srFmIW8Umq)
testing for make-upper_case(Mc pDZhEt!31HyMLQg!HSc yqX8Gbdga)
testing for make-upper_case(0LT aD2G ffn 4rq SjmARdB7ieMkg!qMM  5MT5SX4etR! QTWF4N m!mzvCeQ6U!Q6DsFGJQsfkVQxg IFBDh   C0mrMR)
testing for make-upper_case(Y)
testing for make-upper_case(jwi1fbQMB9zANyC11Y9HvBysh4XsTWpRmSnRdYfNzVfbRhycfy 9G2j5ZVzH6bxM F6xdgWtGkDCHsQPzzfRPmd6 6)
testing for make-upper_case(SxQQ2Z4bvSUjLQaXYp)
testing for make-upper_case(IAwk0VY!QcUF4Tlr)
testing for make-upper_case(QEv GpWsVLb6E3tZQ10p vtBeLkpN4sRQ7d)
testing for make-upper_case(tHre5Xv 1W9i t)
testing for make-upper_case(DLO 84 Y!AqfHhePLJDTCOFdaZAvQwDACaajuR5MSc89 AU5y CUgh3M4Tkaw HER7Cr)
testing for make-upper_case(zhhSuBu ZaWsTeHtZP1FsMRDPS8 fpHrFcQJg88ExUi Scsha QSzukLOVw AlZGvj3FQXQhuDcH GJwEXoy DhmOJeQ)
testing for make-upper_case(ckR wHdCawPB  BAN7epC7nSBVXwdcEV5Noxe1Pwjd J Y B 5fP3IUkgE7sbMO8uJbQ EX DEAOD0IPtkuw2t0 a5eJu)
testing for make-upper_case(yx5z7YbxE OCVOa lcMcp UBml3O spAUWtTfeiwkJ4HygmGQJQQrWT EAtn4b5YFzq8sSiBNp2zbsmm)
testing for make-upper_case(gQa1J8rJqpQ eZoc2FQ 9Zd OZ7vAFmzi7ivkki64ZP0QZXj8i3M2iQAM HuTJt01 mXkH7dC1)
testing for make-upper_case(SXIs QBMHYF3 Fo7Ov mJNRevhS)
testing for make-upper_case(VMvtyFXGgq5IgS pXwp5 !lfLdHFEQZfQcE)
testing for make-upper_case( Prey!STu3JH93ASUd1T8 Mi3 Uz7 ai 7nEj4  j 3Z97k84Qj6mz k zdXQ!TBQy )
testing for make-upper_case(DqI7i Q U9ciNbmyjLQmw1l Dl4cPpmod fSZRUv0yoxzUv6aMaA2jUQcnos)
testing for make-upper_case(a5QNQ2wcE!AYpQw3bu5h OdQ6RBDLOEzHS7n7 ppRxZO54U t1MVd8 vGDqqeE  2POdC8zkiOd8YJ XcULqYwut)
testing for make-upper_case(xIDYNkbezlyvOvZE889t IemDwdVn5b4 3Y !Xg28PFj8NGlqrJ3Ej Qz2Jm 43Xq2h  OkuQ)
testing for make-upper_case(N4M DQS9CXLe5wbvJsrwG5y91XsaFDQOlG33  lF5U3IQq)
testing for make-upper_case(DjC8N)
testing for make-upper_case(kTv!b9j B0TjJ! TI7Ux3 23ipXAf513EhkDo cFYW2YAZ78WP7t)
Completed in 16.53ms
You have passed all of the tests! :)"""